version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: mon_conteneur_mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo